"""MCSA output formatting — Slack alerts and Confluence documents.

Each formatter takes a report markdown string and returns a formatted version
for the target channel.
"""
from __future__ import annotations

from datetime import datetime


# ---------------------------------------------------------------------------
# Slack formatting
# ---------------------------------------------------------------------------

def format_slack_daily(agency_name: str, module: str, report: str) -> str:
    """Format a daily alert for Slack delivery.

    Slack uses mrkdwn (not standard markdown):
    - *bold*, _italic_, ~strikethrough~
    - > blockquote
    - ``` code blocks ```
    - No ## headers — use *bold* lines instead
    """
    today = datetime.now().strftime("%A %d %B %Y")
    icon = _module_icon(module)

    header = f"{icon} *{_module_title(module)} — {agency_name}*\n_{today}_\n"
    divider = "---"

    # Convert markdown headers to Slack bold
    body = report
    for level in ("#### ", "### ", "## ", "# "):
        body = body.replace(level, "*")
        # Close the bold on the same line
        lines = body.split("\n")
        fixed = []
        for line in lines:
            if line.startswith("*") and not line.endswith("*") and line.count("*") == 1:
                line = line + "*"
            fixed.append(line)
        body = "\n".join(fixed)

    # Truncate for Slack (4000 char limit per message)
    if len(body) > 3500:
        body = body[:3500] + "\n\n_...report truncated. Full version on Confluence._"

    return f"{header}\n{divider}\n\n{body}"


def format_slack_summary(agency_name: str, module: str, report: str) -> str:
    """Format a weekly/monthly summary for Slack — shorter than Confluence version."""
    today = datetime.now().strftime("%A %d %B %Y")
    icon = _module_icon(module)

    # Extract just the first ~2000 chars as a summary
    summary = report[:2000]
    if len(report) > 2000:
        summary += "\n\n_Full report available on Confluence._"

    header = f"{icon} *{_module_title(module)} — {agency_name}*\n_{today}_\n"
    return f"{header}\n---\n\n{summary}"


# ---------------------------------------------------------------------------
# Confluence formatting
# ---------------------------------------------------------------------------

def format_confluence(agency_name: str, module: str, cadence: str, report: str) -> str:
    """Format a report for Confluence — standard markdown with metadata header."""
    now = datetime.now()
    date_str = now.strftime("%d %B %Y")
    time_str = now.strftime("%H:%M")

    metadata = (
        f"| Field | Value |\n"
        f"|-------|-------|\n"
        f"| **Agency** | {agency_name} |\n"
        f"| **Module** | {_module_title(module)} |\n"
        f"| **Cadence** | {cadence.title()} |\n"
        f"| **Generated** | {date_str} at {time_str} |\n"
        f"| **Classification** | Internal — not for client distribution |\n"
        f"| **System** | MCSA v1.0 — Tomorrow AI Operating System |\n"
    )

    title = f"# {_module_title(module)} — {agency_name}\n\n"

    confidence_note = (
        "\n\n---\n\n"
        "> **Confidence note:** This report was generated by the Market & Competitor "
        "Surveillance Agent using publicly available data. All competitive claims "
        "require human editorial review before use in external communications.\n"
    )

    return f"{title}{metadata}\n\n---\n\n{report}{confidence_note}"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _module_icon(module: str) -> str:
    return {
        "registry": "[REG]",
        "linkedin": "[LI]",
        "industry": "[IND]",
        "diff": "[DIFF]",
        "website": "[WEB]",
    }.get(module, "[?]")


def _module_title(module: str) -> str:
    return {
        "registry": "Competitor Registry Update",
        "linkedin": "LinkedIn Intelligence",
        "industry": "Industry Publications & Key People",
        "diff": "Competitive DIFF Analysis",
        "website": "Website Pattern Analysis",
    }.get(module, module.title())
